# Generated by Django 4.2.7 on 2023-11-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="technology",
            name="job",
        ),
        migrations.AddField(
            model_name="job",
            name="technologies",
            field=models.ManyToManyField(related_name="jobs", to="web.technology"),
        ),
    ]
