# Generated by Django 4.2.7 on 2024-01-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="experience",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
